# Beware! This file is public by definition
default: &default
  default_team_name: 'IKIA'
  metadata_field: 'https://iederkindisanders.nl'
  # This settings is included only for the specs. Don't remove
  test_setting: 'test123'
  project_title: 'Ieder kind is anders'
  project_start_date: '2020-04-20'
  project_end_date: '2024-04-20'
  feature_toggles:
    allow_distribution_export: true
  distribution_export_min_responses: 1
  logo:
    favicon: 'myfavicon.ico'
    mentor_logo: 'logo_mentor.png'
    student_logo: 'logo_student.png'
    fallback_logo: 'logo.png'
  registration:
    subject_line: Je bent door je ouders uitgenodigd om mee te doen aan het IKIA onderzoek!
    text: Klik op de knop hieronder om een account aan te maken bij Ieder Kind Is Anders.
development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
