apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svc-questionnaires
  namespace: sdv-mvp-master
  labels:
    app: svc-questionnaires
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - svc-questionnaires.app.sportdatavalley.nl
    secretName: sportdatavalley-svc-questionnaires-tls
  rules:
  - host: svc-questionnaires.app.sportdatavalley.nl
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: svc-questionnaires-service
            port:
              number: 3000

